# Generated by Django 5.1.5 on 2025-01-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('universitas', models.CharField(max_length=50)),
                ('cerita', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=50)),
                ('lulusan', models.CharField(max_length=50)),
                ('tempat', models.CharField(max_length=50)),
                ('is_true', models.BooleanField()),
            ],
        ),
    ]
