# Generated by Django 5.1.5 on 2025-01-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='databs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('pw', models.CharField(max_length=50)),
            ],
        ),
    ]
