# Generated by Django 5.1.5 on 2025-01-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
